# Generated by Django 3.2.9 on 2021-12-24 14:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report', models.CharField(max_length=200, verbose_name='报告名')),
                ('userid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '生成的报告文件',
                'verbose_name_plural': '生成的报告文件',
                'db_table': 'report',
            },
        ),
        migrations.CreateModel(
            name='personcase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reportname', models.CharField(max_length=200, verbose_name='报告名')),
                ('systemName', models.CharField(max_length=200, verbose_name='测试系统')),
                ('modelName', models.CharField(max_length=200, verbose_name='模块名称')),
                ('caseName', models.CharField(max_length=200, verbose_name='用例名称')),
                ('status', models.CharField(max_length=10, verbose_name='运行结果')),
                ('runTime', models.DecimalField(decimal_places=2, max_digits=20)),
                ('caseFile', models.CharField(max_length=200, verbose_name='文件名')),
                ('descript', models.CharField(max_length=200, verbose_name='用例描述')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '用例运行结果',
                'verbose_name_plural': '用例运行结果',
                'db_table': 'personCase',
            },
        ),
        migrations.CreateModel(
            name='case_file',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='文件名')),
                ('file', models.FileField(upload_to='', verbose_name='文件地址')),
                ('upload_time', models.DateTimeField(auto_now_add=True, verbose_name='上传时间')),
                ('f_num', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '用户上传用例文件',
                'verbose_name_plural': '用户上传用例文件',
            },
        ),
    ]
