# Generated by Django 3.2.9 on 2021-12-22 11:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('TestApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='case_file',
            options={'verbose_name': '用户上传用例文件', 'verbose_name_plural': '用户上传用例文件'},
        ),
        migrations.CreateModel(
            name='report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report', models.CharField(max_length=200, verbose_name='报告名')),
                ('userid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '生成的报告文件',
                'verbose_name_plural': '生成的报告文件',
                'db_table': 'report',
            },
        ),
    ]
